version: "3.4"
services:
  # duckling-server:
  #   image: rasa/duckling:latest
  #   ports:
  #   - 8000:8000
  #   networks:
  #   - all

  rasa-server:
    image: rasa-bot:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
      - ./actions:/app/actions
      - ./data:/app/data
    command:
      bash -c "rm -rf /app/models/* && rasa train && rasa run --model /app/models --enable-api --cors \"*\" --debug \
      --endpoints /app/endpoints.yml \
      -p 8080"
    ports:
      - "5006:5005"
    public: true
    networks:
      - all

  rasa-actions-server:
    image: rasa-bot:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
      - ./actions:/app/actions
    command: ["rasa", "run", "actions"]
    ports:
      - "5055:5055"
    networks:
      - all

  flask-server:
    image: rasa-bot:latest
    working_dir: /app
    build: "./"
    restart: always
    command: "python app.py"
    ports:
      - "5500:5500"
    networks:
      - all

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
