version: "3.10"
services:
  rasa-bot:
    image: rasa-bot:latest
    working_dir: /app
    build: "./"
    restart: always
    command: 'rasa run --cors "*"'
    ports:
      - "5006:5005"
    public: true
    networks:
      - all

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
